#application.yml

server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  server:
    response-cache-update-interval-ms: 5000
  client:
    register-with-eureka: false   # euraka의 registry에 등록할지 여부를 설정, 서버기 때문에
    fetch-registry: false         # registy에 있는 정보를 가져올지 여부를 결정
  instance:
    lease-renewal-interval-in-seconds: 5
