# application.yml

server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Hello Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: lb://USER-SERVICE

        - id: place-service
          predicates:
            - Path=/place-service/**
          uri: lb://PLACE-SERVICE

#      filters:
#        - CustomFilter




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka